FROM golang:1.19-alpine3.16 as builder

ADD . /wow_client
WORKDIR /wow_client

RUN go build -v -o /tmp/wow_client ./cmd/client

FROM alpine:3.16

COPY --from=builder /tmp/wow_client /usr/bin/wow_client

RUN chmod +x /usr/bin/wow_client

ENTRYPOINT ["wow_client"]